# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Diet', 'Diet'), ('Fashion', 'Fashion'), ('Exercise', 'Exercise')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='gallary/')),
                ('Image_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='galla.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('NationalPark', 'NationalPark'), ('Gymstore', 'Gymstore'), ('ParadiceLost', 'ParadiceLost'), ('TreebeadsTexas', 'TreebeadsTexas'), ('MombasaCity', 'MombasaCity')], max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='galla.Location'),
        ),
    ]
