# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('DC', 'DC'), ('Marvel', 'Marvel')], default='category', max_length=120),
        ),
    ]
