# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0002_auto_20180928_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Fashion', 'Travel'), ('Food', 'Food')], default='category', max_length=120),
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(blank=True, to='galla.Category'),
        ),
    ]
