# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0004_auto_20180928_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='galla.Category'),
        ),
    ]
