# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0005_auto_20180928_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(default='category', max_length=50, verbose_name='Category'),
        ),
    ]
