# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0006_auto_20180928_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Nation Park', 'Nation Park'), ('Bonfire Adventures', 'Bonfire Adventures'), ('Paradice Lost', 'Paradice Lost'), ('Hardstone-Ottawa', 'Hardstone-Ottawa'), ('Treebeads-Texas', 'Treebeads-Texas'), ('Mombasa-City', 'Mombasa-City')], max_length=120),
        ),
    ]
