# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0008_auto_20180928_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='galla.Category'),
        ),
    ]
