# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0009_auto_20180928_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=120),
        ),
    ]
