# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0010_auto_20180928_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
