# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0011_auto_20180928_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pub_date',
            new_name='post_date',
        ),
    ]
