# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0013_auto_20180930_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
