# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0014_auto_20180930_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Workout', 'Food')], max_length=120),
        ),
    ]
