# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0015_auto_20180930_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Workout', 'Workout')], max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('National Park', 'National Park'), ('Gym-store', 'Gym-store'), ('Paradice Lost', 'Paradice Lost'), ('Protus-Restaurant', 'Protus-Restaurant'), ('Treebeads-Texas', 'Treebeads-Texas'), ('Mombasa-City', 'Mombasa-City')], max_length=120),
        ),
    ]
