# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0017_auto_20180930_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='Category',
        ),
    ]
