# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0020_auto_20181001_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('NationalPark', 'NationalPark'), ('Gymstore', 'Gym-store'), ('ParadiceLost', 'Paradice Lost'), ('TreebeadsTexas', 'Treebeads-Texas'), ('MombasaCity', 'Mombasa-City')], max_length=120),
        ),
    ]
