# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0034_auto_20190514_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Diet', 'Diet'), ('Fashion', 'Fashion'), ('Exercise', 'Exercise')], max_length=120),
        ),
    ]
